spring:
    application:
        name: CalculoDeduccionesBackEnd
    datasource:
        url: jdbc:mysql://localhost:3306/calculo_deducciones?CreateDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: infinity
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            connection-timeout: 30000
            pool-name: HikariPool-CALCULO_DEDUCCIONES
            auto-commit: true
            connection-test-query: SELECT 1
            validation-timeout: 5000
            leak-detection-threshold: 2000
            initialization-fail-timeout: 0
            max-lifetime: 1800000
            allow-pool-suspension: true
            register-mbeans: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                useLocalSessionState: true
                rewriteBatchedStatements: true
                cacheResultSetMetadata: true
                cacheServerConfiguration: true
                elideSetAutoCommits: true
                maintainTimeStats: false
                useUnicode: true
                characterEncoding: utf8
                characterSetResults: utf8
                useSSL: false
                useLegacyDatetimeCode: false
                serverTimezone: UTC
                allowPublicKeyRetrieval: true
                connectionCollation: utf8_general_ci
                zeroDateTimeBehavior: convertToNull
                useJDBCCompliantTimezoneShift: true
    jpa:
        database: mysql
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        open-in-view: true
logging:
    level:
        org.springframework.integration: DEBUG

springdoc:
    show-actuator: true
